[package]
name = "demo_23_09"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure="0.1.2"
failure_derive="0.1.2"
